project:
  type: website
  output-dir: docs
website:
  title: "gabriella-scolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd
      - Class_Assignments.qmd
format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

